# Numpy
### یک کتابخانه قدرتمند در زبان برنامه‌نویسی پایتون است که امکان ایجاد و مدیریت آرایه‌های چندبعدی و انجام عملیات علمی و ریاضی موثر را فراهم می‌کند. این کتابخانه ابزارهایی برای انجام عملیات جبرخطی، تبدیل فوریه، محاسبات آماری، تولید اعداد تصادفی، و سایر وظایف علمی را فراهم می‌سازد

####  نوشته شده و اجرا میشود C سرعت زیاد در محاسبات این کتابخانه به این دلیل هست که با زبان 


In [199]:
# ما قراره از این کتابخونه توی برنامه خیلی استفاده کنیم
# پس میایم یک اسم مختصر رو براش تغریف میکنیم که راحت تر بتونیم صداش بزنیم
import numpy as np
import math    # کنارش همیشه باشه به درد میخوره

# هست رو به اسم یک کتابخانه ذخیره نکن چون باعث خطای ایمپورت حلقوی واشکال در سیستم میشه : توجه py  هیچ وقت فایل اسکریپت پایتون رو که پسوندش

In [200]:
import numpy as np 

print(np.__version__) # ==> نمایش ورژن

1.26.4


# سه تا تعریف مهم 

### آرایه (Array):
آرایه یک مجموعه‌ی مرتب از عناصر است که هر عنصر در آن به یک نمایه یا اندیس دسترسی دارد. این عناصر می‌توانند از همان نوع یا انواع مشخصی باشند. آرایه‌ها در بسیاری از زبان‌های برنامه‌نویسی و کتابخانه‌های علمی مورد استفاده قرار می‌گیرند و اغلب برای ذخیره و کار با داده‌های چند بعدی و عملیات ماتریسی مورد استفاده قرار می‌گیرند

### ماتریس (Matrix):
ماتریس یک نوع خاص از آرایه است که دارای دو بُعد (سطر و ستون) است. عناصر ماتریس معمولاً از یک نوع مشخصی هستند (مانند اعداد حقیقی یا اعداد صحیح) و از نمادهای ریاضی برای نمایش واحد‌ها و اعداد در سطرها و ستون‌ها استفاده می‌شود. ماتریس‌ها در ریاضیات، علوم کامپیوتر، فیزیک، و بسیاری از حوزه‌های دیگر به عنوان ابزار مهمی برای نمایش و پردازش داده‌ها مورد استفاده قرار می‌گیرند

### لیست (List):
لیست یک داده‌ساختار پویا در برنامه‌نویسی است که می‌تواند شامل عناصری از هر نوع باشد. لیست به ترتیب عناصر را ذخیره می‌کند و امکان افزودن، حذف، و تغییر عناصر در آن وجود دارد. در بسیاری از زبان‌های برنامه‌نویسی، لیست یک ساختار داده پرکاربرد و اساسی است


#### record data : یعنی تعداد سطر ها
#### feature : یعنی ستون ها
#### [1,2,3] ---> یک رکورد دیتا
#### [[1,2] [3,4]] --> دو تا رکورد دیتا

---------------------------------------------------------------------

# Numpy عملگر ها در 

In [201]:
import numpy as np
x = np.array([0,1,2,3]) # تولید آرایه یک بعدی

print('x = ', x)
print()

print('x + 5 = ', x + 5)
print('np.add(x, 5) = ', np.add(x, 5))
print()

print('x - 2 = ', x - 2)
print('np.subtract(x, 2) = ', np.subtract(x, 2))
print()

print('x * 3 = ', x * 3)
print('np.multiply(x, 3) = ', np.multiply(x, 3))
print()

print('.5 * x = ', 0.5 * x)
print('np.multiply(0.5, x) = ', np.multiply(0.5, x))
print()

print('-x = ', -x *2) # ضرب در 2- شده اند
print('np.negative(x) = ', np.negative(x))
print()

print('x ** 2 = ', x ** 2)
print('np.power(x, 2) = ', np.power(x, 2))
print()

print('x / 2 = ', x / 2)
print('np.divide(x, 2) = ', np.divide(x, 2))
print()

print('x // 2 = ', x // 2)
print('np.floor_divide(x, 2) = ', np.floor_divide(x, 2))
print()

print('x % 2 = ', x % 2)
print('np.mod(x, 2) = ', np.mod(x, 2)) # باقی مانده


x =  [0 1 2 3]

x + 5 =  [5 6 7 8]
np.add(x, 5) =  [5 6 7 8]

x - 2 =  [-2 -1  0  1]
np.subtract(x, 2) =  [-2 -1  0  1]

x * 3 =  [0 3 6 9]
np.multiply(x, 3) =  [0 3 6 9]

.5 * x =  [0.  0.5 1.  1.5]
np.multiply(0.5, x) =  [0.  0.5 1.  1.5]

-x =  [ 0 -2 -4 -6]
np.negative(x) =  [ 0 -1 -2 -3]

x ** 2 =  [0 1 4 9]
np.power(x, 2) =  [0 1 4 9]

x / 2 =  [0.  0.5 1.  1.5]
np.divide(x, 2) =  [0.  0.5 1.  1.5]

x // 2 =  [0 0 1 1]
np.floor_divide(x, 2) =  [0 0 1 1]

x % 2 =  [0 1 0 1]
np.mod(x, 2) =  [0 1 0 1]


-------------------

# 1- (Vector) تولید بردار 
### آرایه یک بعدی همان بردار تلقی می شود

In [202]:
arr = np.array([1, 2, 3, 4, 5]) 
print(arr)
print(type(arr))
print(arr.shape)  # برای بدست آوردن ابعاد یک آرایه استفاده میشه 

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


# 2- (Matrix) تولید ماتریس

In [203]:
# روش اول با مقادیری از لیست np.array
arr_2 = np.array([[1,2,3,4],[5,6,7,8]])  # برای ارایه دوبعدی و بالاتر داخل یک جفت کروشه همشون قرار می گیرند الان اینجا 2 سطر میشه در 4 ستون
print(arr_2)
print()

arr_3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 
print(arr_3)

print()
print(type(arr_3))

print('================================')

# np.matrix روش دوم
# این جا هم عملا یک لیست را میدهیم به عنوان ورودی
arr_1 = np.matrix([[-1,4,7],[4,9,1]])
print(arr_1 )  

print()

list_2d = [[-1, 4, 7], [4, 9, 1]]   # ساخت ماتریس از یک لیست دوبعدی
arr_from_list = np.matrix(list_2d)
print(arr_from_list)

print()
print(type(arr_from_list))

print('================================')

# تبدیل لیست به آرایه روش سوم  asarray
my_list = [1, 2, 3, 4, 5] # ایجاد یک لیست

# NumPy تبدیل لیست به یک آرایه 
my_array = np.asarray(my_list)

print("NumPy آرایه  ایجاد شده:")
print(my_array)

print()
print(type(my_array))

[[1 2 3 4]
 [5 6 7 8]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

<class 'numpy.ndarray'>
[[-1  4  7]
 [ 4  9  1]]

[[-1  4  7]
 [ 4  9  1]]

<class 'numpy.matrix'>
NumPy آرایه  ایجاد شده:
[1 2 3 4 5]

<class 'numpy.ndarray'>


------------
# slicing & indexing & reshape

In [204]:
arr_1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr_slice = arr_1[1:7:2]  # یعنی از ایندکس شماره 1 تا ایندکس شماره 7 به صورت 2 تا 2 تا رو به جلو حرکت کنه
print(arr_slice)

print()

arr_2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) # الان یک ماتریس 3 در 4 داریم
print('arr_2 : ','\n', arr_2)
print()
arr_slice = arr_2[1:3 , 1:3]  # اولی برای محدوه سطر ها و دومی محدوده ستون ها هست 
print(arr_slice) # اینطوری میشه که از سطر ها ایندکس شماره 1 تا 3  و ستون ها هم از ایندکس 1 تا 3 رو انتخاب کن
print('\n')

print('=========================================================================================')

# دسترسی به عناصر ارایه

print('arr_2 : ','\n', arr_2 , '\n')
print(arr_2[1]) # در اینجا معنی این رو میده که یعنی سطر اول چون دو بعدی بود
print(arr_2[1, 1]) # سطر اول ستون شماره 1 بعد 0  یا ایندکس شماره 1
print(arr_2[0, 0])
print(arr_2[2, 1])

# چاپ ایتم دوم تمام سطرها
print(arr_2[:, 1])

# چاپ ایتم اول تمام ستون ها
print(arr_2[0, :])

# چاپ ایتم های بین دوم و چهارم در ستون اول
print(arr_2[1:3, 0])

row_r1 = arr_2[1, :]    
row_r2 = arr_2[1:2, :]
col_r1 = arr_2[:, 1]
col_r2 = arr_2[:, 1:2]

[2 4 6]

arr_2 :  
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 6  7]
 [10 11]]


arr_2 :  
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[5 6 7 8]
6
1
10
[ 2  6 10]
[1 2 3 4]
[5 9]


# تغییرات در آرایه فرعی  زیر مجموعه آرایه اصلی در آرایه اصلی هم اعمال میشه

In [205]:

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('a : \n' , a , '\n')

b = a[:2, 1:3] # یعنی سطر ها تا ایندکس شماره 2   و ستون ها هم از ستون شماره 1 نه 0  تا ستون شماره 3
print('b : \n' , b , '\n')

print()

# با تغییر یک زیر ارایه از یک ارایه اصلی اطلاعات ارایه اصلی هم تغییر خواهد کرد،  چون یک زیر ارایه یک نمایی از یک ارایه اصلی هستش

# اولا میدونیم که : a[0, 1] = b[0, 0]  ====> طبق دو تا آرایه بالا میشه این نتیجه رو بدست آورد

print('a[0, 1] : ',a[0, 1])   # ===> "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print('a[0, 1]',a[0, 1])   # ===> "77"


a : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

b : 
 [[2 3]
 [6 7]] 


a[0, 1] :  2
a[0, 1] 77


# تغییر شکل آرایه که چند در چند نشان بده

In [206]:
arr_1 = np.array([[1,2,3,4],[5,6,7,8]]).reshape(4,2)  #  با این میشه اون چیدمان رو عوض کرد فقط ضربشون باید با قبلی برابر بشه یا تعداد عناصر برابر باشه
print(arr_1)

print("\n")

arr_2 = np.arange(1,16) # خودش اگر خودکار تولید کنه خطی مینویسه حالا در پایین میخواهم عوض کنم
print(arr_2)
print()

arr_3 = np.arange(1,16).reshape(5,3) # در این جا اون بالایی عوض شده ابعادش
print(arr_3)
print()

arr_4 = np.arange(1,16).reshape(3,5) # این هم همون بالایی هست فقط برعکس شده و نکته مهم این است که باید ضربشون درست باشه
print(arr_4)
print("\n")

arr_5 = np.arange(1,21, dtype= int).reshape(5,4)  # پیش فرض  نوع داده همون عدد صحیح هست
print(arr_5)  
print()

arr_6 = np.arange(1,21 , dtype= float ).reshape(5,4)
print(arr_6)
print()



[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]]



# اعمال توابع روی محور ها

# 

In [207]:
arr_3 = np.arange(6).reshape((2,3)) # یک آرایه 6 تایی خطی که به ماتریس 2 در 3 تغییر یافته
print(arr_3)
print("=================")
print(np.mean(arr_3))         # این تابع میانگین کل ماتریس رو محاسبه خواهد کرد
print("=================")
print(np.mean(arr_3, axis=0)) # این روش میانگین هر ستون
print("=================")
print(np.mean(arr_3, axis=1)) # و این روش هم میانگین هر سطر رو خروجی میده


[[0 1 2]
 [3 4 5]]
2.5
[1.5 2.5 3.5]
[1. 4.]


------------------------------------------------------------------
# برای تولید خودکار بردار و آرایه ها
<br>

## 1- arange() : ایجاد بردار با اعداد متوالی  

In [208]:
arr_1 = np.arange(1,10) # خود پایتون ، محدوده range() همون شبیه به 
print(arr_1)
print()

arr_2 = np.arange(1,16,2)   # مثل محدوده خود عدد 16 حساب نمیشه و طول گام دو تا دو تا
print(arr_2)
print() 

arr_3 = np.arange(0, 2 * np.pi , 0.2) # np.pi ====> میشه oo همان عدد پی در ریاضی که به صورت پراپرتی تعریف شده نه این کلا مقادیر ثابت مثل بی نهایت که 
print(arr_3)
print()

arr_4 = np.arange(0,1,0.01) # بالا نیست !!! بلکه گفتیم که 0 تا 1 رو هر دفعه به اندازه یک صدم برو جلو که عملا میشه صد قسمت چون خوود عدد 1 نیست ولی از اون طرف هم از 0 شروع میشه num این اون 
print(arr_4)
print()

# ایجاد یک ارایه با فاصله یکنواخت
print(np.arange(10,25,5)) # start , stop , step

[1 2 3 4 5 6 7 8 9]

[ 1  3  5  7  9 11 13 15]

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2]

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]

[10 15 20]


## 2- linspace() : ایجاد بردار با تعداد مشخص از اعداد متوالی

In [209]:
arr_1 = np.linspace(1,5) # تحویل میده float تکه می کند و در ضمن num = 50 پیش فرض 
print(arr_1)
print()

arr_2 = np.linspace(1,5,num = 5) 
print(arr_2)
print()

arr_3 = np.linspace(1,5,num = 5 , dtype= int )
print(arr_3) 
print()

arr_4 = np.linspace(1,5,num = 5 , dtype= int , endpoint = True)  # هست یعنی  خود عددآخری رو هم حساب می کنه  True همون endpoint پیش فرض 
print(arr_4) 
print()

# برای تولید اعداد تصادفی تکراری در بازه ای که میخوای
arr_5 = np.linspace(1,5,num = 35 , dtype= int , endpoint = False)  # الان شروع می کنه که تکراری بزنه چون همشون عدد صحیح اند و بازه هم کوچک هست و تعداد قسمت یا همون برش ها هم زیاد پس تکراری خواهیم داشت و خود عدد آخری هم حساب نمیشه یعنی نباید 5 داشته باشیم
print(arr_5) 


[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]

[1. 2. 3. 4. 5.]

[1 2 3 4 5]

[1 2 3 4 5]

[1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4]


## نتیجه : برای تولید اعداد متوالی
## 1- linspace() : num و همراه با پارامتر float اعداد متوالی از جنس 
## 2- arange() : پایتون range() و عملکردی مشابه همان int اعداد متوالی از جنس 

<br>
<br>

## 3- logspace() : (برای ایجاد یک آرایه نرمال با توان توان‌های لگاریتمی با اختلاف یکسان )

In [210]:
""" numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0) ==>  روی همون 50 هست num این جا هم مقدار 

        start و stop: حد پایین و حد بالای محدوده مورد نظر
        num: تعداد نقاطی که در محدوده مشخص شده تولید می‌شوند (پیش‌فرض ۵۰)
        endpoint: مشخص می‌کند که آیا stop در نقاط تولید شده قرار می‌گیرد یا خیر (پیش‌فرض True)
        base: پایه لگاریتم (پیش‌فرض ۱۰)
        dtype: نوع داده مورد نظر برای آرایه تولید شده
        axis: محوری که در آن آرایه تولید می‌شود
"""

arr_1 = np.logspace(1,5 , num =5 ) # واجبه که بنویسی چون بد در میاد اعداد num این جا اون 
print(arr_1)     # [1.e+01 1.e+02 1.e+03 1.e+04 1.e+05] : میگه 10 به توان 1  و 10 به توان 2 و تا 10 به توان 5
print()

arr_2 = np.logspace(1,3 , num =3 , dtype= int )  # الان این جا داره توان های 10 را چاپ می کنه 
print(arr_2)
print()

arr_3 = np.logspace(1,3 , num = 3 , dtype= int  , base= 2)  # این جا گفتم که توان های 2 رو چاپ کن چون خودش پیشفرض 10 هست برای همون بالا از توان های 10 تولید می کرد
print(arr_3)
print()

arr_4 = np.logspace(start=1,stop=3 , num = 3 , dtype= int  , base= 5 )  # این جا گفتم که توان های 5 رو چاپ کن
print(arr_4)
print()

arr_5 = np.logspace(1,15 , num = 15 , dtype= int  , base= 5).reshape(5,3) # این جت هم شکلش عوض شده
print(arr_5)
print()

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]

[  10  100 1000]

[2 4 8]

[  5  25 125]

[[          5          25         125]
 [        625        3125       15625]
 [      78125      390625     1953125]
 [    9765625    48828125   244140625]
 [ 1220703125 -2147483648 -2147483648]]



# 4- geomspace() : (برای ایجاد یک آرایه هندسی  با دنباله هندسی )

In [211]:
arr_1 = np.geomspace(1,9 , num = 9 )  # یک آرایه هندسی از عدد ۹ ایجاد می کنه که حاوی اعدادی است که به ازای هر دو مقدار متوالی، نسبت نسبتی ثابت دارند
print(arr_1)
print()

arr_2 = np.geomspace(10, 1000, num=7)
print(arr_2)
print()


[1.         1.31607401 1.73205081 2.27950706 3.         3.94822204
 5.19615242 6.83852117 9.        ]

[  10.           21.5443469    46.41588834  100.          215.443469
  464.15888336 1000.        ]



# 5-  ایجاد اعداد تصادفی و ماتریس‌های تصادفی

In [212]:
arr_1 = np.random.randint(11) #  یک عدد در یک بازه برمیگرداند
print(arr_1)
print(type(arr_1)) # <class 'int'>
print('=======================')

arr_2 = np.random.randint(1,11,10)  # low , high , size  ===> عدد رندوم در اون بازه برمیگرداند  size به تعداد پارامتر 
print(arr_2)
print(type(arr_2)) # <class 'numpy.ndarray'>
print('=======================')

arr_3 = np.random.choice(10,10) # high , size : مثل بالایی هست تقریبا ولی فرقش اینه که میتونه غیر تکراری هم تولید کنه
print(arr_3)

print()

arr_3 = np.random.choice((0,10),10) # این جا یعنی که از این 2 تا عدد 0 و 10  به تعداد 10 تا تولید کن
print(arr_3)

print()

arr_4 = np.random.choice(10,10 , replace = False)  # رو مثلا 11 بنویسی که تکراری هم باشه بین اعداد خطا میده و نهایتش همون عدد هست size برای حذف تکرار از آرایه واگر بیشتر وارد کنی 
print(arr_4)

print()

two_tas_duplicates = np.random.choice(6,2) +1  # پرتاب دو تاس با ارقام تکراری
print(two_tas_duplicates) # با عدد 1 در آخر جمع شده چون از 0 میشماره تا یکی کمتر

print()

two_tas_no_duplicates = np.random.choice(6,2 , replace  = False) +1  # پرتاب دو تاس که جفت نیاره  یعنی تکراری نداشته باشیم
print(two_tas_no_duplicates)
print()

print('=======================')

# : برای تولید اعداد تصادفی غیرتکراری در بازه 0 و 1  
# 1- np.random.default_rng() : برای ایجاد یک ژنراتوراز کلاس نامپای که اعداد تصادفی تولید می کنه ، برای برنامه های حرفه ای
# 3- np.random.random(n) : بشه reshape برای تولید اعداد تصادفی در بازه [0, 1) به صورت تکراری  و خطی که در ضورت نیاز باید 
# 2-  np.random.randn(m,n) : شده تحویل میده چون سطر ستون میگیره برخلاف بالایی که سطری تولید می کنه reshape برای تولید اعداد تصادفی از توزیع نرمال ، این خودش در اصل 

rng = np.random.default_rng()  
arr_1 = rng.random(6).reshape(2,3) # بشه reshape اول تعدادی که میخواهی میدهی و بعدش سطر و ستون مورد نیاز را میدی بهش در صورتی که بخواهی 
print(arr_1)
print('---------------')

# ایجاد یک ارایه با ایتم های تصادفی از 0 تا1  100 تا عدد میده
print (np.random.random(100))

print()

# همون بالایی فقط اندازه اش 2در 2 باشه الان به جای 100 تا شد 4 تا عدد 
M = np.random.random((2,2))
print (M)
print('---------------')

arr_random_normal = np.random.randn() # ساخت ماتریس با مقادیر تصادفی گوسی (نرمال)  به ترتیب سطر و ستون را میدهی ،اگر چیزی ننویسی فقط یک عدد برمیگرداند
print(arr_random_normal)


1
<class 'int'>
[8 3 8 3 7 6 3 7 7 4]
<class 'numpy.ndarray'>
[1 3 1 4 4 6 0 2 3 4]

[ 0 10 10 10  0 10  0 10  0 10]

[7 6 2 1 4 0 8 5 3 9]

[2 6]

[5 1]

[[0.04662353 0.02517256 0.76226339]
 [0.79882062 0.19114703 0.20581795]]
---------------
[0.85509216 0.10933529 0.72751811 0.58089867 0.09683576 0.22954203
 0.03998878 0.33441899 0.53823556 0.66974842 0.46235987 0.87427015
 0.39149836 0.51176117 0.2851049  0.51165035 0.92282334 0.45487447
 0.03376802 0.85346252 0.27953623 0.58540065 0.81579833 0.27073838
 0.73587875 0.03333523 0.37921358 0.26149492 0.18491126 0.98192105
 0.99268895 0.90074791 0.30291024 0.56886539 0.85517408 0.49916367
 0.30794256 0.29682255 0.27817393 0.38409175 0.05838424 0.28953849
 0.67609624 0.85323983 0.19971001 0.50698759 0.09579341 0.46150396
 0.57658834 0.78662304 0.38587799 0.96044146 0.19774226 0.06078174
 0.02166482 0.74836246 0.41407807 0.41648376 0.51580181 0.67669624
 0.17919335 0.08734893 0.47062064 0.24097731 0.40657914 0.30828368
 0.25223913 0.84484

# 6- آرایه های خاص 

In [213]:
# 1- ماتریس صفر
print("zeros arr_2rices:")
zeros = np.zeros((3,4) , dtype= int) # داخلش یک تاپل میدی که به ترتیب سطر و ستون هست
print(zeros)
print()

zeros = np.zeros(12) .reshape(3,4)  # تبدیل شد به 3در 4 مثل بالایی reshape این دیگه خطی بود اول ولی با 
print(zeros)
print()

print()

# 3 تا ماتریس صفر یکسان
print(np.zeros((3,2,3))) # پارامتر آخر یعنی چند تا میخوام از اون تولید بشه

print("================================")

# 2- ماتریس یک

print("ones arr_2rices:")
ones = np.ones((3,4),dtype= int)
print(ones)

ones = np.ones(12) # استفاده کنیم و همون حالت رو ایجاد کنیم reshape این هم میشه مثل بالا از 
print(ones)
print()

print("================================")

# 3- ماتریس خالی
print("empty arr_2rices:")
empty = np.empty((3,4))
print(empty)  # مقادیری که ایجاد می کنه تقریبا صفرهست ولی صفر نیست و این یک فضای خالی رو بوجود می آورد
print()

print("================================")

# ایجاد یک ارایه پر
print("full arr_2rices:")
full = np.full((2,2),7) # که همه اعداد داخلش عدد 7 است
print(full)

print()

full_2 = np.full((3,3), True, dtype=bool) # آرایه سه در سه با مقدار بولین
print(full_2)

print()

full_3 = np.full((3,3),3)
print(full_3)

print("================================")

# 4- ماتریس همانی یا همان واحد 

print("identity matrix  (identity):")
identity_arr_2rix_1 = np.identity(3) 
print(identity_arr_2rix_1)
print()

print("identity matrix (eye):")
identity_arr_2rix_2 = np.eye(3)
print(identity_arr_2rix_2)

# هر دو ماتریس معادلی با همانی را نشان می‌دهند که در ابعاد 3 در 3 و با مقادیر عناصر روی قطر اصلی برابر 1 و سایر عناصر برابر 0 هستند

print('---------')

# ضرب ماتریس -اسکالر
# میشه یک عدد رو در یک ماتریس ضرب کرد مثلا این جا در یک ماتریس همانی عدد 2 رو ضرب کردیم
diagonal_arr_2rix = 2 * np.eye(4)
print(diagonal_arr_2rix)
print()

zeros arr_2rices:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
ones arr_2rices:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

empty arr_2rices:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

full arr_2rices:
[[7 7]
 [7 7]]

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

[[3 3 3]
 [3 3 3]
 [3 3 3]]
identity matrix  (identity):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

identity matrix (eye):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---------
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]



# Copy & view

In [214]:
"""
کپی (Copy):
    یک کپی از یک آرایه یک نسخه جدید از داده‌ها است
    هرگونه تغییری که در کپی اعمال شود، مستقل از آرایه اصلی است و برعکس
    کپی مالکیت داده‌های خود را دارد
    است، به معنی اینکه کپی مستقل از آرایه اصلی است None کپی base ویژگی
    این اتفاق می افتد view اگر به آبجکت اصلی و اولیه اشاره کرد یعنی مالکیت ندارد که در 

دید (View):
    فقط یک دید از داده‌ها است و داده‌ها اصلی را به اشتراک می‌گذارد
    تغییرات متناظر در آرایه اصلی را تاثیر می‌گذارد و بالعکس view، هر تغییری در 
    مالکیت خود را ندارد view
    اطلاعات خود را از آرایه اصلی دریافت می‌کند و تغییرات را به آن منتقل می‌کند view به آرایه اصلی اشاره می‌کند به این معنی که view در base ویژگی 
"""

#  اگر ورودی از نوع آرایه نامپای باشد، یک نسخه کپی شده از آن برگردانده می‌شود
# باشد یک ارایه نامپای جدید ایجاد می شود iterable  اگر ورودی از نوع لیست، تاپل، یا سایر توابع

import numpy as np

# ایجاد یک آرایه اصلی
original_array = np.array([1, 2, 3, 4, 5])

# ایجاد یک کپی از آرایه اصلی
copied_array = np.copy(original_array)

# تغییرات در کپی
copied_array[0] = 100

# نمایش آرایه اصلی و کپی
print("Original array:", original_array)  # Output: [1 2 3 4 5]
print("Copied array:", copied_array)      # Output: [100   2   3   4   5]

print('===============================')

# ایجاد یک آرایه اصلی
original_array = np.array([1, 2, 3, 4, 5])

# از آرایه اصلی view ایجاد یک 
view_array = original_array[:3]

# view تغییرات در 
view_array[0] = 100

# view نمایش آرایه اصلی و 
print("Original array:", original_array)  # Output: [100   2   3]


Original array: [1 2 3 4 5]
Copied array: [100   2   3   4   5]
Original array: [100   2   3   4   5]


# بررسی استفاده علامت های بزرگ تر و کوچک تر 

In [215]:
a = np.array([[1,2], [3, 4], [5, 6]])

print('a :  \n', a , '\n')

bool_idx = (a > 2)   # ایتم هایی با مقدار بیشتر از ۲ را پیدا کن
                     # این روش یک ارایه دقیقا به همان سایز را برمیگرداند که ایتم های ان از نوع بولین میباشند

print(bool_idx)  # [[False False]
                 # [ True  True]
                 # [ True  True]]

print('-----------------------------')

# حالا از ارایه بدست آمده استفاده میکنیم تا ایتم هایی راکه مقدار آنها بیشتر از  ۲میباشد را از ارایه اصلی استخراج کنیم
print(a[bool_idx])  # [3 4 5 6]

print('-----------------------------')

# همچنین تمام مراحل بالا را میتوانیم توی یک خط بنویسیم
print(a[a > 2])   #[3 4 5 6]

a :  
 [[1 2]
 [3 4]
 [5 6]] 

[[False False]
 [ True  True]
 [ True  True]]
-----------------------------
[3 4 5 6]
-----------------------------
[3 4 5 6]


# برای فهمیدن این که یک شرط در کجاها برقرار شده است داخل آرایه

In [234]:
arr_3 = np.random.randint(1,5,7) 
print('arr_3 : \n',arr_3)
print()
pos = np.where(arr_3 == 3) # np.where() ولی این باید ایندکس ها کار می کنه متد 
print(pos) 
print()

arr_4 = np.random.randint(1,5,7) 
print('arr_4 : \n',arr_4)
print()
pos = np.where(arr_4 > 3) # کجا ها یا مکان هایی که بزرگ تر از 3 میاد رو نشون میده
print(pos) 
print()

print('=================')

arr_5 = np.random.randint(1,7,10)  # مثلا یک تاس 10 بار پرتب کردیم 
print(arr_5)
print()

pos = np.where(arr_5 % 2 == 0 ) # یعنی اون ایندکس هایی که زوج هستند رو پیدا کنه
print(pos) # یا به عبارتی احتمال این که چند بار زوج بیاد رو نشون بده

# حالا برای این که تعداد اون چند بار شرط اعمال شده رو بفهمیم 2 راه وجود داره
# این جا شرط تعداد زوج بودن در اعدادی که در آرایه بود رو نشون میدهد
print('The number of condition compliance' ,len(pos[0]))  # چون یک تاپله و عضو اولش هم همین مورد مارو نشون میده نوشتم ایندکس اول
print('The number of condition compliance' ,np.size(pos)) # برای فهمیدن تعداد کل عناصر آرایه 


arr_3 : 
 [1 4 2 2 3 1 2]

(array([4], dtype=int64),)

arr_4 : 
 [2 2 4 3 4 4 4]

(array([2, 4, 5, 6], dtype=int64),)

[2 1 1 2 5 3 4 4 3 2]

(array([0, 3, 6, 7, 9], dtype=int64),)
The number of condition compliance 5
The number of condition compliance 5


# replace

In [217]:
my_array = np.array(['apple','banana','orange'])
new_array = np.char.replace(my_array,'apple','reza')
print(new_array)

my_array = np.array([1, 2, 3, 4, 5])
str_array = np.char.array(my_array.astype(str))   # Convert elements to strings
new_array = np.char.replace(str_array, '2', '3')  # Replace '2' with '3'
print(new_array)

print('===========================')

my_array = np.array([1, 2, 3 ,4, 5, 6])
new_value = 8
replaced_array = np.where(my_array== 6, new_value, my_array)
print(my_array)

print('===========================')

arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
arr[arr %2 == 1] = -1
print(arr)

print('===========================')

arr = np.array([1, 2, 3])

# Iterating over the elements of the array with buffered flag and specifying the data type as strings
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['int']):
    print(x)

"""" 
پارامتر flags:

    readonly: این پرچم باعث می‌شود که عناصر آرایه به صورت فقط خواندنی  باشند و هرگونه تغییر در آنها ممنوع می‌شود

    readwrite: این  به کاربر اجازه می‌دهد تا عناصر آرایه را به عنوان قابل خواندن و نوشتن  استفاده کند و می‌تواند تغییرات را در آنها اعمال کند

    writeonly: این تنها به کاربر اجازه می‌دهد تا در آرایه نوشته شود و از آن خواندن ممنوع است

    allocate: این مشخص می‌کند که در صورت لزوم برای آرایه‌های ورودی که به عنوان ورودی به تابع داده شده‌اند، حافظه اضافی تخصیص داده شود

    buffered: این باعث می‌شود یک بافر پیوسته برای دسترسی به عناصر آرایه فراهم شود، که می‌تواند بهینه‌سازی عملکرد را فراهم کند


پارامتر op_dtypes:

    int: با استفاده از این پارامتر می‌توانید تمام عملیات‌ها را با عناصر داده شده به عنوان اعداد صحیح انجام دهید

    float: این پارامتر باعث می‌شود که تمام عملیات با عناصر داده شده به عنوان اعداد ممیز شناور انجام شود

    complex:(complex) با استفاده از این پارامتر می‌توانید با اعداد مختلط  کار کنید

    bool: (boolean)با استفاده از این پارامتر می‌توانید با مقادیر منطقی  کار کنید
    
    S :  عناصر به صورت رشته با نوع داده‌ی بایت چاپ می شوند

    object: این پارامتر به شما اجازه می‌دهد با استفاده از اعضای آرایه به عنوان شیء  کار کنید و به آنها دسترسی داشته باشید
"""

['reza' 'banana' 'orange']
['1' '3' '3' '4' '5']
[1 2 3 4 5 6]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]
1
2
3


'" \nپارامتر flags:\n\n    readonly: این پرچم باعث می\u200cشود که عناصر آرایه به صورت فقط خواندنی  باشند و هرگونه تغییر در آنها ممنوع می\u200cشود\n\n    readwrite: این  به کاربر اجازه می\u200cدهد تا عناصر آرایه را به عنوان قابل خواندن و نوشتن  استفاده کند و می\u200cتواند تغییرات را در آنها اعمال کند\n\n    writeonly: این تنها به کاربر اجازه می\u200cدهد تا در آرایه نوشته شود و از آن خواندن ممنوع است\n\n    allocate: این مشخص می\u200cکند که در صورت لزوم برای آرایه\u200cهای ورودی که به عنوان ورودی به تابع داده شده\u200cاند، حافظه اضافی تخصیص داده شود\n\n    buffered: این باعث می\u200cشود یک بافر پیوسته برای دسترسی به عناصر آرایه فراهم شود، که می\u200cتواند بهینه\u200cسازی عملکرد را فراهم کند\n\n\nپارامتر op_dtypes:\n\n    int: با استفاده از این پارامتر می\u200cتوانید تمام عملیات\u200cها را با عناصر داده شده به عنوان اعداد صحیح انجام دهید\n\n    float: این پارامتر باعث می\u200cشود که تمام عملیات با عناصر داده شده به عنوان اعداد ممیز شناور انجام شود\n\n    complex:(complex) با استفاده از ای

# پیمایش روی آرایه ها

In [240]:
import numpy as np

# e ایجاد آرایه دوبعدی 
e = np.array([[1, 2, 3], [4, 5, 6]])
print('e : \n' , e ,'\n')

iterator = np.nditer(e)
for element in iterator:
    print(element, end=', ')
    

e : 
 [[1 2 3]
 [4 5 6]] 

1, 2, 3, 4, 5, 6, 

# برای فهمیدن تعداد کل عناصر آرایه 

In [219]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.size)

# برای فهمیدن نوع عناصر موجود در آرایه
# data type --> dtype

print(arr.dtype)  # int32 :  یعمی یک عدد صحیح 32 بیتی

# برای فهمیدن اندازه آرایه ها برحسب بایت
print(arr.itemsize)


8
int32
4


# فهمیدن چند بعدی بودن آرایه


In [220]:
arr_1 = np.array([1,2,3,4,5,6])
print(arr_1.ndim)   

arr_2 = np.array([[1,2,3,4],[5,6,7,8]])  # ارایه دو بعدی یا ماتریس
print(arr_2.ndim)

1
2


# فهمیدن تعداد سطر و ستون در یک آرایه


In [221]:
arr_1 = np.array([1,2,3,4,5,6])  
print(arr_1.shape)  # اگر یک بعدی باشه فقط تعداد عناصر رو مینویسه

arr_2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2.shape)  # عدد اولی تعداد سطر و دومی تعداد ستون ها یک تاپل برمیگرداند

(6,)
(2, 4)


# تغییر شکل آرایه که چند در چند نشان بده

In [222]:
arr_1 = np.arange(1,21 , dtype= complex).reshape(5,4)
print(arr_1)

arr_2 = np.arange(27).reshape((3,3,3))
print(arr_2)

[[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j]
 [ 5.+0.j  6.+0.j  7.+0.j  8.+0.j]
 [ 9.+0.j 10.+0.j 11.+0.j 12.+0.j]
 [13.+0.j 14.+0.j 15.+0.j 16.+0.j]
 [17.+0.j 18.+0.j 19.+0.j 20.+0.j]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


# مرتب کردن اعضای یک ماتریس یا آرایه

In [223]:
arr_1 = np.array([5,2,9,-1,3,8,2])
arr_1_sort= np.sort(arr_1)
print(arr_1_sort)

print()

arr_2 = np.matrix([[-1,4,7],[4,9,1]])
print(arr_2)   
arr_2_sort = arr_2.sort()   # این جا هم از روش متدی استفاده کردم همون هست
print(arr_2_sort)

# مرتب کردن ماتریس به هصورت صعودی
print('\n','Sorting the matrix in ascending order : ')
sorted_matrix = np.sort(arr_2,axis=None) # ===> استفاده کنیم reshape ماتریس یک بعدی برمیگرداند که برای مرتب کردن میتونیم از 
print(sorted_matrix)

print()

# مرتب‌سازی ماتریس به صورت یک بعدی به صورت نزولی
sorted_matrix_descending = np.sort(arr_2, axis=None)[::-1]

# چاپ ماتریس مرتب به صورت نزولی
print('Sorting the matrix in descending order:')
print(sorted_matrix_descending)


[-1  2  2  3  5  8  9]

[[-1  4  7]
 [ 4  9  1]]
None

 Sorting the matrix in ascending order : 
[[-1  1  4  4  7  9]]

Sorting the matrix in descending order:
[[-1  1  4  4  7  9]]


# تغییرات روی عناصر ماتریس یا آرایه

In [224]:
import numpy as np

# ایجاد یک آرایه
arr = np.array([1, 2, 3, 4, 5])

# حذف عنصر با اندیس 2
arr_deleted = np.delete(arr, 2)
print("After deleting element at index 2:", arr_deleted)

# افزودن عنصر 10 در انتهای آرایه
arr_appended = np.append(arr_deleted, 10)
print("After appending element 10:", arr_appended)

# درج عنصر 100 در اندیس 2
arr_inserted = np.insert(arr_appended, 2, 100)
print("After inserting element 100 at index 2:", arr_inserted)

# تغییر اندازه آرایه به اندازه 8
arr_resized = np.resize(arr_inserted, 8)
print("After resizing array to size 8:", arr_resized)

After deleting element at index 2: [1 2 4 5]
After appending element 10: [ 1  2  4  5 10]
After inserting element 100 at index 2: [  1   2 100   4   5  10]
After resizing array to size 8: [  1   2 100   4   5  10   1   2]


# کاهش ابعاد آرایه squeeze(),flatten(),revel()

In [225]:
import numpy as np

# ایجاد یک آرایه سه بعدی با بعد اضافی
arr = np.array([[[1], [2], [3]], 
                [[4], [5], [6]]])

print('arr : ', '\n', arr , '\n')


print(f'شکل آرایه قبل از squeeze:{arr.shape}\n')

print("آرایه تبدیل شده با squeeze:")
# استفاده از squeeze برای کاهش بعد اضافی
arr_squeezed = np.squeeze(arr)
print(arr_squeezed)
print("\nشکل آرایه بعدی پس از squeeze:", arr_squeezed.shape)

print('-----------------------------------')

# یک آرایه یک بعدی را به شکلی دو بعدی با تنها یک ستون
print(f'reshape شکل آرایه قبل از :{arr.shape}\n')

# تغییر شکل آرایه به یک آرایه دو بعدی با یک ستون
arr_reshaped = arr.reshape(-1, 1)

print("reshape(-1, 1) آرایه تغییر شکل یافته با:")
print(arr_reshaped)

print('\nکاهش یک بعد ')
arr_squeezed = np.squeeze(arr_reshaped)

print(arr_squeezed)

print('===========================================','\n')

# استفاده از flatten برای تبدیل به یک آرایه یک بعدی
print(f'شکل آرایه قبل از flatten:{arr.shape}\n')

arr_flattened = arr.flatten()
print("آرایه تبدیل شده با flatten:")
print(arr_flattened)

print("شکل آرایه بعدی پس از flatten:", arr_flattened.shape , '\n')

print('-----------------------------------')

"""""
numpy.ravel(a, order='C') :
        a: آرایه چند بعدی که می‌خواهید آن را به یک آرایه یک بعدی تبدیل کنید
        order: برای ایجاد به ترتیب ردیفی C نحوه ایجاد آرایه یک بعدی پیش فرض مقدار 
"""""

print(f'شکل آرایه قبل از ravel:{arr.shape}\n')


# تبدیل آرایه چند بعدی به آرایه یک بعدی
ravel_arr = np.ravel(arr)
print("آرایه تبدیل شده با ravel:")
print(ravel_arr)

print("شکل آرایه بعدی پس از ravel:", ravel_arr.shape)

# ====================================================================================

# نتیجه گیری : 

# کاهش یک بعد      =====> squeeze   , reshape(-1,1)
# رساندن به یک بعد =====> flatten() , revel()

# تفاوت flatten() , revel(): در نحوه بازگشت داده‌ها است
# flatten() : یک کپی از آرایه اصلی را برمی‌گرداند 
# ravel() :  یک نمایش مشتق از آرایه را برمی‌گرداند، بنابراین هرگونه تغییر در آرایه را به آرایه اصلی انعکاس می‌دهد



arr :  
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]] 

شکل آرایه قبل از squeeze:(2, 3, 1)

آرایه تبدیل شده با squeeze:
[[1 2 3]
 [4 5 6]]

شکل آرایه بعدی پس از squeeze: (2, 3)
-----------------------------------
reshape شکل آرایه قبل از :(2, 3, 1)

reshape(-1, 1) آرایه تغییر شکل یافته با:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

کاهش یک بعد 
[1 2 3 4 5 6]

شکل آرایه قبل از flatten:(2, 3, 1)

آرایه تبدیل شده با flatten:
[1 2 3 4 5 6]
شکل آرایه بعدی پس از flatten: (6,) 

-----------------------------------
شکل آرایه قبل از ravel:(2, 3, 1)

آرایه تبدیل شده با ravel:
[1 2 3 4 5 6]
شکل آرایه بعدی پس از ravel: (6,)


# concattenate اضافه کردن دو یا چند ماتریس به یکدیگر

In [226]:
# برای تبدیل کردن بردار ها به عنوان ستون ها یا سطر های یک ماتریس و بردار ها باید هم اندازه باشند در چند مورد زیر رعایت شوند حتما

# 1- جمع بردار ها 

# این ها الان بردار های ما هستند مثلا
a = np.array([1,5])  
b = np.array([4,7]) 
c = np.array([7,10])

# way 1 : 

# np.column_stack() :
# این تابع برای اتصال آرایه‌های یک بعدی به عنوان ستون به سطرهای یک آرایه دو بعدی استفاده می‌شود. به عبارت دیگر، این تابع آرایه‌های یک بعدی را به عنوان ستون‌های جدید به یک آرایه دو بعدی اضافه می‌کند
abc_columns = np.column_stack((a,b,c))   # به عنوان ستون یک ماتریس در نظر گرفته شده اند یا به عبارتی به طور عمودی اضافه شده اند
print(abc_columns)
print()

abc_rows = np.row_stack((a,b,c)) # به عنوان سطر  ماتریس اضافه شده اند یا به عبارتی اضافه شدن از نوع افقی صورت گرفته
print(abc_rows)
print()

print('-------------------------------------')

# way 2 : 

# افزودن به صورت افقی
a = np.array([1,4])
b = np.array([6,7])
ab_horizontal = np.concatenate((a,b))
ab_horizontal = np.hstack((a, b))
print(ab_horizontal)
print()

# افزودن به صورت ستونی
ab_vertical = np.vstack((a, b))
print(ab_vertical)
print()

print('-------------------------------------')

# way 3 :

# np.concatenate() :
# ین تابع برای اتصال یک سری از آرایه‌ها به یکدیگر در طول یک محور معین استفاده می‌شود. محوری که می‌خواهید آرایه‌ها در آن اتصال یابند، به عنوان پارامتر ورودی به این تابع تعیین می‌شود

x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y]) #  اضافه می شوند y و بعدش  x تبدیل به یک ارایه یک بعدی ولی یک جا به صورت که اول مقادیر

[[ 1  4  7]
 [ 5  7 10]]

[[ 1  5]
 [ 4  7]
 [ 7 10]]

-------------------------------------
[1 4 6 7]

[[1 4]
 [6 7]]

-------------------------------------


array([1, 2, 3, 4, 5, 6])

# split  تقسیم یک آرایه به چند زیر آرایه

In [227]:
# way 1 : 
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5]) # یعنی تقسیم به 3 تا زیر آرایه و باید در ایندکس های 3تا5 یعنی دوتا چون میشه 3-5
print(x1)
print(x2)
print(x3)

print('==============================')

# way 2 : 
grid = np.arange(16).reshape((4,4))
print(grid)

upper,lower = np.vsplit(grid,2)
print(grid,'\n')
print(upper,'\n')
print(lower,'\n')

print('-------------')

left,right = np.hsplit(grid,2)
print(grid,'\n')
print(left,'\n')
print(right,'\n')

print('==============================')

# way 3 :

# np.array_ split() : آرایه را در خلال امتداد تعیین شده در ورودی با پارامتر تقسیم می کند

import numpy as np

array = np.arange(10)
result = np.array_split(array, 3)
print(result)

print('----------------')

# ایجاد یک بردار اعداد صحیح برای ماتریس هم میشه کلا آرایه نوشتم
arr_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])
print(arr_1)
print()

# # تقسیم بردار به تعداد زیر آرایه‌های مشخص شده
subarrays = np.array_split(arr_1, 3)  # از ابعاد بالاتر شروع می کنه به تقسیم کردن یعنی اولی رو بزرگ در نظر میگیره
print(subarrays)
print()

# # نمایش زیر آرایه‌ها
for i, subarray in enumerate(subarrays):
    print(f"subarray{i + 1}: {subarray}")

print('\n')

# ایجاد یک ماتریس به عنوان ورودی
arr_2rix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# تقسیم ماتریس به تعداد زیر ماتریس‌های مشخص شده
subarr_2rices = np.array_split(arr_2rix, 3, axis=0)  # axis=1 تقسیم بر حسب ردیف‌ها یا سطری البته ستونی هم میشه 

# نمایش زیر ماتریس‌ها
for i, subarr_2rix in enumerate(subarr_2rices):
    print(f"subarray{i + 1}:\n{subarr_2rix}")

[1 2 3]
[99 99]
[3 2 1]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]] 

-------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
----------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13]

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9]), array([10, 11, 12, 13])]

subarray1: [1 2 3 4 5]
subarray2: [6 7 8 9]
subarray3: [10 11 12 13]


subarray1:
[[1 2 3]]
subarray2:
[[4 5 6]]
subarray3:
[[7 8 9]]


-----------------
# Broadcasting

In [228]:
# قانون Broadcasting : در هر دو آرایه داده یکسان باشد؛ یا مقدار بُعد آخرِ حداقل یکی از آرایه ها برابر باشد shape باید اندازه ی محور نهایی یا همان مقدار آخرین

import numpy as np

# دو آرایه با اشکال مختلف
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # shape: (2, 3)
arr2 = np.array([10, 20, 30])             # shape: (3,) but numpy with Broadcasting convert to : (2, 3)

# اعمال جمع بین دو آرایه
result = arr1 + arr2

print(result)


[[11 22 33]
 [14 25 36]]


# Work with date and time

In [229]:
import numpy as np
# datetime64 استفاده از تاریخ و زمان فعلی برای ساخت یک شی از    
# از کتابخانه ای در زبان پایتون با همین نام برگرفته شده است

today = np.datetime64('now')
print(today)

day = np.datetime64('2024-03-04')
print(day)

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)

tomorrow = np.datetime64('today') + np.timedelta64(1, 'D')
print(tomorrow)

print('=============================================')

# ... تبدیل اطلاعات امروز گرفته شده از نامپای به سال و روز و
# تبدیل شیء datetime64 به رشته با فرمت "YYYY-MM-DD"

today = np.datetime64('now')

date_year_month = np.datetime_as_string(today, unit='M')
print("Year-Month:", date_year_month)

date_year_month_day = np.datetime_as_string(today, unit='D')
print("Year-Month-Day:", date_year_month_day)

time_hour_minute = np.datetime_as_string(today, unit='m')
print("Hour-Minute:", time_hour_minute)

print('=============================================')

dt_25s = np.dtype('timedelta64[25s]')
unit_info = np.datetime_data(dt_25s)

print(unit_info)



2024-04-19T07:12:16
2024-03-04
2024-04-18
2024-04-20
Year-Month: 2024-04
Year-Month-Day: 2024-04-19
Hour-Minute: 2024-04-19T07:12
('s', 25)


# (خواندن از دیسک) ذخیره آرایه های نامپای و وارد کردن 

In [230]:
import numpy as np

# ایجاد آرایه
my_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np.save('my_arr', my_arr) # .npy ذخیره یک آرایه با پسوند

# .npy خواندن آرایه از فایل 
loaded_arr = np.load('my_arr.npy')
print("Loaded Array:")
print(loaded_arr)

print('-----------------')

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
np.savez('filename.npz', array1=array1, array2=array2)  # .npz ذخیره چندین آرایه در یک فایل 

#.npz بارگیری داده‌ها از فایل 
loaded_data = np.load('filename.npz')

print(loaded_data.keys())

# npz چاپ کلیدها و آرایه‌های موجود در فایل 
print("Loaded Array:")
for key in loaded_data.keys():
    print(key + ":", loaded_data[key])


print('==========================================')

# CSV ذخیره داده‌ها به صورت 
data_to_save = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.savetxt('filename.csv', data_to_save, delimiter=',')     # csv ذخیره به صورت 

# CSV بارگیری داده‌ها از فایل 
loaded_array = np.genfromtxt('filename.csv', delimiter=',')
print("Loaded Array:")
print(loaded_array)

print('==========================================')

array = np.array([1, 2, 3, 4, 5])
np.savetxt('filename.txt', array)    # ذخیره داده‌ها به صورت متنی

# np.loadtxt() بارگیری داده‌ها از فایل متنی با استفاده از 
loaded_array = np.loadtxt('filename.txt',skiprows=0 ,unpack=False)
print("Loaded Array:")
print(loaded_array)


# پارامتر skiprows: این پارامتر تعیین می‌کند که چند سطر از ابتدای فایل باید نادیده گرفته شود

# پارامتر unpack: این پارامتر مشخص می‌کند که آیا داده‌های خوانده شده باید در یک آرایه یک بعدی یا در آرایه‌های مجزا قرار گیرند
    #True : داده‌های هر ستون به ترتیب در آرایه‌های جداگانه قرار می‌گیرند که به تعداد ستون‌های موجود در فایل متنی است
    #False (یا این پارامتر را حذف کنید) :  داده‌های خوانده شده به صورت یک آرایه دو بعدی ذخیره می‌شوند


Loaded Array:
[1 2 3 4 5 6 7 8 9]
-----------------
KeysView(NpzFile 'filename.npz' with keys: array1, array2)
Loaded Array:
array1: [1 2 3]
array2: [4 5 6]
Loaded Array:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Loaded Array:
[1. 2. 3. 4. 5.]
