# Numpy (قسمت دوم)
## سایر اعمال روی ماتریس ها

In [1]:
import numpy as np
import math 

In [2]:
np.random.seed(0) # ==> تولید مجدد دیتا

ar_1 = np.random.randint(10,size = 6) # یک آرایه یک بعدی  با 6 تا عدد
ar_2 = np.random.randint(10,size = (3,4)) # یک آرایه دو بعدی با 3 سطر و 4 ستون
ar_3 = np.random.randint(10,size = (3,4,5)) # یک آرایه 3 بعدی در 3 تا در 4سطر و 5 ستون

print('array_1: \n',ar_1,'\n')
print('array_2 :\n ',ar_2,'\n')
print('array_3 :\n ',ar_3,'\n')

array_1: 
 [5 0 3 3 7 9] 

array_2 :
  [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

array_3 :
  [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]] 



# اطلاعات بیشتر در مورد ماتریس

In [3]:
print(f'ar_3 ndim : {ar_3.ndim}') # number of dimension
print(f'ar_3 shape : {ar_3.shape}')
print(f'ar_3 size : {ar_3.size}') #==> 3*4*5

print(f'ar_3 dtype: {ar_3.dtype}') #==> data type
print('item size : ',ar_3.itemsize,'bytes')
print('nbytes : ',ar_3.nbytes,'bytes')

ar_3 ndim : 3
ar_3 shape : (3, 4, 5)
ar_3 size : 60
ar_3 dtype: int32
item size :  4 bytes
nbytes :  240 bytes


In [4]:
print(ar_1[0],'\n')

print(ar_2[0]) # یعنی سطر 0
print(ar_2[0,0]) # (0,0) یعنی عنصر
ar_2[0,0] = 7 # عوض کرن یا دستکاری آرایه
print(ar_2[0,0],'\n') # (0,0) یعنی عنصر

print(ar_3[0],'\n')
print(ar_3[0,0],'\n' )
print(ar_3[0,0,0],'\n' )

ar_3[0,0,0] = np.pi # عدد اعشاری هست
print(ar_3[0,0,0]) # ==> در نظر گرفتیم int به عدد 3 تغییر میده در حالی که باید به 3.1415 تغییر بده و این علتش اینه که بالا از نوع 

5 

[3 5 2 4]
3
7 

[[8 1 5 9 8]
 [9 4 3 0 3]
 [5 0 2 3 8]
 [1 3 3 3 7]] 

[8 1 5 9 8] 

8 

3


# slice

## یک بعدی

In [5]:
x = np.arange(1,10)

x[:4]

array([1, 2, 3, 4])

In [6]:
x[4:7]

array([5, 6, 7])

In [7]:
x[::2]

array([1, 3, 5, 7, 9])

In [8]:
x[1::2]

array([2, 4, 6, 8])

In [9]:
x[::-1] # همه مقادیر برعکس می شوند

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

## چند بعدی

In [10]:
print(ar_2,'\n') # برای خود تابع پرینت نیست با اون فرق داره این مقداریه مثل بقیه چیز ها end الان اون\n این 

[[7 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 



In [11]:
print(ar_2[:,0]) # همه سطر ها و ستون 0

[7 7 1]


In [12]:
print(ar_2 [:2,:3]) # یعنی دو سطر و سه ستون)

[[7 5 2]
 [7 6 8]]


In [13]:
ar_2[:3,::2] # تمامی سطر ها و ستون ها یکی در میان

array([[7, 2],
       [7, 8],
       [1, 7]])

In [14]:
ar_2[::-1,::-1]  # یعنی جای همه عناصر سطر ها باهم برعکس بشه و همچنین برای ستون ها هم برعکس شوند

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 7]])

# عملگرهای ریاضی

In [15]:
import numpy as np

# جمع دو آرایه
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result_add = np.add(arr1, arr2)
print("جمع دو آرایه:")
print(result_add)

# تفریق دو آرایه
result_subtract = np.subtract(arr1, arr2)
print("\nتفریق دو آرایه:")
print(result_subtract)

# ضرب دو آرایه
result_multiply = np.multiply(arr1, arr2)
print("\nضرب دو آرایه:")
print(result_multiply)

# تقسیم دو آرایه
result_divide = np.divide(arr1, arr2)
print("\nتقسیم دو آرایه:")
print(result_divide)


جمع دو آرایه:
[5 7 9]

تفریق دو آرایه:
[-3 -3 -3]

ضرب دو آرایه:
[ 4 10 18]

تقسیم دو آرایه:
[0.25 0.4  0.5 ]


# عملگرهای مقایسه‌ای

In [16]:
# برابری دو آرایه
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 5, 3])
result_equal = np.equal(arr1, arr2)
print("برابری دو آرایه:")
print(result_equal)

# نابرابری دو آرایه
result_not_equal = np.not_equal(arr1, arr2)
print("\nنابرابری دو آرایه:")
print(result_not_equal)

# بزرگتر بودن اولین آرایه نسبت به دومین آرایه
result_greater = np.greater(arr1, arr2)
print("\nبزرگتر بودن اولین آرایه نسبت به دومین آرایه:")
print(result_greater)

# کوچکتر بودن اولین آرایه نسبت به دومین آرایه
result_less = np.less(arr1, arr2)
print("\nکوچکتر بودن اولین آرایه نسبت به دومین آرایه:")
print(result_less)

برابری دو آرایه:
[ True False  True]

نابرابری دو آرایه:
[False  True False]

بزرگتر بودن اولین آرایه نسبت به دومین آرایه:
[False False False]

کوچکتر بودن اولین آرایه نسبت به دومین آرایه:
[False  True False]


# عملیات روی آرایه ها (Vectorization)  

# آرایه های یک بعدی

In [17]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

# جمع عناصر دو آرایه به صورت برداری
result_vectorized_addition = array1 + array2

# ضرب عناصر دو آرایه به صورت برداری
result_vectorized_multiplication = array1 * array2

# چاپ نتایج
print("آرایه اول:", array1)
print("آرایه دوم:", array2)
print("جمع برداری دو آرایه:", result_vectorized_addition)
print("ضرب برداری دو آرایه:", result_vectorized_multiplication)

آرایه اول: [1 2 3 4 5]
آرایه دوم: [10 20 30 40 50]
جمع برداری دو آرایه: [11 22 33 44 55]
ضرب برداری دو آرایه: [ 10  40  90 160 250]


# ارایه های دو بعدی و بالاتر

In [18]:


A = np.arange(1,7).reshape(2,3)
B = np.arange(7,13).reshape(2,3)

print(A , '\n')
print(B , '\n')

print(f'suarr_2ion : \n {A+B} \n')  # به صورت عنصر به عنصر  و حق نداریم که ابعاد ماتریس ها متفاوت باشه
print(f'subtract : {A-B}')  
print(f'foreign multiplication  : \n {A * B}\n') # برای ضرب خارجی باید ابعاد برابر باشند 
print(f'divide: {A/B}')

# (n,k),(k,m)->(n,m)  توجه : برای ضرب داخلی باید رعایت بشه 
# می کنیم که ابعاد مثل هم نشوند تا عملیات ضرب  داخلی انجام بشه B پس الان مثال بالا رو بخش 
# نتیجه ضرب داخلی یک عدد هست نه یک بردار

A = np.arange(1,7).reshape(2,3)
B = np.arange(7,13).reshape(3,2)            
print(f'inner prodoct : \n {A @ B}')
print(f'inner prodoct : \n {A.dot(B)}')

# الان دیگه این ها از کار افتادند چون ابعاد برابر نشدند و خطا خواهیم داشت
# print(f'suarr_2ion : {A+B}')  
# print(f'subtract : {A-B}') 
# print(f'divide: {A/B}')

print('--------------------------------------------------------------')

A = np.arange(1,7).reshape(2,3) #  [[1 2 3]
# #                                  [4 5 6]]

print(f"sum rows :    {A.sum(axis= 1)}")  # برای جمع کردن سطر ها 
print(f"sum columns : {A.sum(axis= 0)}")  # برای جمع کردن ستون ها 

print(A.cumsum(axis= 1)) # جمع انباشتگی سطری  یعنی اولیین خونه خودشه بقیه عناصر هارو با قبلی جمع می کنه میزاره اون جا  و ستون اخر همون جمع سطر ها میشه اگر دقت کنی همون ماتریس  اولی در میاد ستون آخرش
print(A.cumsum(axis= 0)) # این دفعه ستون ها رو با هم جمع می کنه سطر اولی میمونه سطر دومیا میشوند جمع خودشون با بالایی ها


[[1 2 3]
 [4 5 6]] 

[[ 7  8  9]
 [10 11 12]] 

suarr_2ion : 
 [[ 8 10 12]
 [14 16 18]] 

subtract : [[-6 -6 -6]
 [-6 -6 -6]]
foreign multiplication  : 
 [[ 7 16 27]
 [40 55 72]]

divide: [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
inner prodoct : 
 [[ 58  64]
 [139 154]]
inner prodoct : 
 [[ 58  64]
 [139 154]]
--------------------------------------------------------------
sum rows :    [ 6 15]
sum columns : [5 7 9]
[[ 1  3  6]
 [ 4  9 15]]
[[1 2 3]
 [5 7 9]]


------------------
# 1- ضرب اسکالر

In [19]:
# یکی از قابلیت های ارایه در نامپای بر خلاف لیست های معمولی در پایتون اینه که این امکان رو دارید
# تا در یک مرجله عملیات ریاضی رو به تمام ایتم های یک ارایه اعمال کنید

arr = np.array([[[1], [2], [3]], [[4], [5], [6]]])

print(arr * 2)
print(arr + arr)
print(arr / 2.0)

print('--------------------')

[[[ 2]
  [ 4]
  [ 6]]

 [[ 8]
  [10]
  [12]]]
[[[ 2]
  [ 4]
  [ 6]]

 [[ 8]
  [10]
  [12]]]
[[[0.5]
  [1. ]
  [1.5]]

 [[2. ]
  [2.5]
  [3. ]]]
--------------------


# 2- ضرب بردار- ماتریسی

In [20]:

# تعریف یک بردار
vector = np.array([1, 2, 3])

# تعریف یک ماتریس
arr_2rix = np.array([[4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# ضرب بردار در ماتریس
result = np.dot(arr_2rix, vector)

# یا با استفاده از عملگر @
# result = arr_2rix @ vector

print("بردار:")
print(vector)
print("\nماتریس:")
print(arr_2rix)
print("\nنتیجه ضرب بردار در ماتریس:")
print(result)


بردار:
[1 2 3]

ماتریس:
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

نتیجه ضرب بردار در ماتریس:
[32 50 68]


# 3- ضرب داخلی بردارها - ضرب ماتریس در بردار - ضرب دو ماتریس

In [21]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))
print()


# arr_2rix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print()

# arr_2rix / arr_2rix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219

[29 67]
[29 67]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## جمع بندی مطالب بالا با یک مثال

In [22]:
# هم ساخت arange میشد با 
x = np.array([[1,2],[3,4]], dtype=np.float64) # x :  [[1. 2.][3. 4.]]
y = np.array([[5,6],[7,8]], dtype=np.float64) # y :  [[5. 6.][7. 8.]]


print(f'suarr_2ion :')  # به صورت عنصر به عنصر عمل می کنه
# جمع المانی که هر باعث ایجاد یک ارایه میشود
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))
print()

print(f'subtract :') 
# تفریق المانی که باعث ایجاد یک ارایه میشود
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))
print()

print(f'foreign multiplication : ') # ضرب خارجی 
# ضرب المانی که باعث ایجاد یک ارایه میشود
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y) # ضرب خارجی 
print(np.multiply(x, y))# ضرب خارجی 
print()

print(f'inner prodoct dot :') 
# ضرب داخلی که باعث ایجاد یک ارایه میشود
# [[19. 22.]
#  [43. 50.]]
print( x@y) # ضرب داخلی
print(x.dot(y)) # ضرب داخلی
print()

print(f'divide: ')
# تقسیم المانی که باعث ایجاد یک ارایه میشود
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))
print()

print(f'sqrt: ')
# ریشه مربعی المانی که باعث ایجاد یک ارایه میشود
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

suarr_2ion :
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]

subtract :
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]

foreign multiplication : 
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]

inner prodoct dot :
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]

divide: 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

sqrt: 
[[1.         1.41421356]
 [1.73205081 2.        ]]

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]

subtract :
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]

foreign multiplication : 
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]

inner prodoct dot :
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]

divide: 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

sqrt: 
[[1.         1.41421356]
 [1.73205081 2.        ]]


------------------------
# Transpose (ترانهاده)

In [23]:
A = np.array([
    [1, 2],
    [3, 4],
    [5,6]
])

print('A : \n',A)

B = A.T
print('Transpose A :\n',B)

B = A.transpose()
print('Transpose A :\n',B)

A : 
 [[1 2]
 [3 4]
 [5 6]]
Transpose A :
 [[1 3 5]
 [2 4 6]]
Transpose A :
 [[1 3 5]
 [2 4 6]]


# Inverse (معکوس)

In [24]:
A=np.array([
    [1,2],
    [3,4]
])

print('A : \n',A)

B=np.linalg.inv(A)
print('B :\n',B)

C = A.dot(B)
print('Inverse A :\n',C)

A : 
 [[1 2]
 [3 4]]
B :
 [[-2.   1. ]
 [ 1.5 -0.5]]
Inverse A :
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# قطر های اصلی و فرعی

In [25]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# مجموعه ای از عناصر قطر اصلی
diag_second = np.diag(A,k=0) # ==> پیشفرض همین 0 هست
print('عناصر قطر اصلی A:\n', diag_second)

# مجموعه ای از عناصر قطر دوم (زیر قطر اصلی)
diag_second = np.diag(A,k=1)
print('عناصر قطر اصلی A:\n', diag_second)

عناصر قطر اصلی A:
 [1 5 9]
عناصر قطر اصلی A:
 [2 6]


# Trace (جمع عناصر روی قطر اصلی و فرعی)

In [26]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print('A : \n',A)

B = np.trace(A)
print('جمع عناصر قطر اصلی A : \n',B)

# مجموعه ای از عناصر قطر دوم (زیر قطر اصلی)
diag_second = np.diag(A,k=1)
s = sum(diag_second)
print('جمع عناصر قطر دوم A:\n', s)

A : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
جمع عناصر قطر اصلی A : 
 15
جمع عناصر قطر دوم A:
 8


# محاسبه میانگین هر سطر 

In [27]:
arr_2 = np.matrix([[-1, 4, 7], [4, 9, 1]])
row_means = np.mean(arr_2, axis=1)
print("Mean of each row:", row_means, '\n')


Mean of each row: [[3.33333333]
 [4.66666667]] 



# محاسبه میانگین هرستون 

In [28]:
arr_2 = np.matrix([[-1,4,7],[4,9,1]])
row_means = np.mean(arr_2, axis=1)
print("Mean of each row:", row_means , '\n')

Mean of each row: [[3.33333333]
 [4.66666667]] 



# Deteminant (دترمینان)

In [29]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.linalg.det(A)
print(f'determinant is : {B}')

determinant is : 0.0


----------------------------
# ریاضی

In [30]:
# sin محاسبه بسط تیلور برای تابع 

# sin(x)≈ x - x^3/3! + x^5/5! - x^7/7! + x^9/9!

# x = float(input('x = '))
# sum = 0
# for i in range(5):  # مثلا تا جمله پنجم
#     sum = sum + np.power(-1,i) * np.power(x , 2*i +1 ) / math.factorial(2*i +1)
# print(f'sin({x}) = {np.sin(x)} , \t  sum = {sum}')  #  نمایش مقدار واقعی تابع سینوس و مقدار محاسبه شده

# print('-----------------------')

# روی ماتریس e محاسبه لگاریتم با مبنا طبیعی یا 

# A = np.arange(1,7).reshape(2,3) 
# print(np.log(A))  

# تغییر مبنا لگاریتم به اعشاری یا همون 10

# A = np.arange(1,7).reshape(2,3)
# print(np.log10(A))

# مبنای 2
# A = np.arange(1,7).reshape(2,3)
# print(np.log2(A))


# print('-----------------------')

# با این کار اون علامت براکت بیرونی میپره چون یک حلقه داره رویش اعمال میشه

# A = np.arange(1,15).reshape(7,2)
# print(A)

# for element in A :
#     print(element)

# print('-----------------------')

# محاسبه جمع سینسوس اعداد رادیکال ۱ تا ۹
# sum = 0
# for i in range(10):
#     sum = sum + np.sin(np.sqrt(i))   
# print(sum)

# print('-----------------------')

# هم استفاده می کنیم math تابع فاکتوریل رو نداره پس برای این که دچار مشکل نشیم در کنارش از ماژول numpy 
 # numpy بالا گفته بودم به درد میخوره ایمپورتش کن چون بعضی از توابع رو نداره 
# print(math.factorial(10)) 


# print(np.exp(1.0)) # تابع exponential
# print(np.pi) # تابع عدد پی
# print(np.sqrt(4)) 

In [31]:
# import numpy as np
# import math

# # 1. جمع دو عدد
# num1 = 5
# num2 = 3
# result_sum = np.add(num1, num2)
# print("1. جمع دو عدد:", result_sum)

# # 2. ضرب دو عدد
# num1 = 4
# num2 = 6
# result_multiply = np.multiply(num1, num2)
# print("2. ضرب دو عدد:", result_multiply)

# # 3. تقسیم دو عدد
# num1 = 8
# num2 = 2
# result_divide = np.divide(num1, num2)
# print("3. تقسیم دو عدد:", result_divide)

# # 4. توان دو عدد
# num1 = 2
# num2 = 3
# result_power = np.power(num1, num2)
# print("4. توان دو عدد:", result_power)

# # 5. معکوس یک عدد
# num = 4
# result_reciprocal = np.reciprocal(num)
# print("5. معکوس عدد:", result_reciprocal)

# # 6. محاسبه بسط تیلور برای تابع sin(x)
# x = float(input('x = '))
# sum_taylor = 0
# for i in range(5):  # مثلا تا جمله پنجم
#     sum_taylor += np.power(-1, i) * np.power(x, 2*i + 1) / math.factorial(2*i + 1)
# print(f'sin({x}) بسط تیلور = {sum_taylor} , \t sin({x}) واقعی = {np.sin(x)}')

# # 7. محاسبه لگاریتم با مبنا طبیعی
# A = np.arange(1, 7).reshape(2, 3)
# print("لگاریتم با مبنای e:")
# print(np.log(A))

# # 8. تغییر مبنا لگاریتم به اعشاری یا همون 10
# print("لگاریتم با مبنای 10:")
# print(np.log10(A))

# # 9. مبنای 2
# print("لگاریتم با مبنای 2:")
# print(np.log2(A))

# # 10. چاپ عناصر ماتریس
# print('ماتریس A:')
# print(A)
# print('عناصر ماتریس به صورت تکی:')
# for element in A:
#     print(element)

# # 11. محاسبه جمع سینوس اعداد رادیکال ۱ تا ۹
# sum_sine = 0
# for i in range(10):
#     sum_sine += np.sin(np.sqrt(i))
# print("جمع سینوس اعداد رادیکال ۱ تا ۹:", sum_sine)

# # 12. استفاده از تابع exponential
# print("تابع exponential از عدد ۱:", np.exp(1.0))

# # 13. استفاده از عدد پی
# print("عدد پی:", np.pi)

# # 14. محاسبه جذر یک عدد
# print("جذر ۴:", np.sqrt(4))
